language: rust
cache: cargo
script:
  - (cargo install mdbook --git https://github.com/azerupi/mdBook.git --force || true)
  - mkdir src
  - echo "[Introduction](introduction.md)\n" >> src/SUMMARY.md
  - |
    for f in $(ls text/* | sort)
    do
        echo "- [$(basename $f ".md")]($(basename $f))" >> src/SUMMARY.md
        mv $f src
    done
  - cp README.md src/introduction.md
  - mdbook build
  - mv -f book/* .
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
  #   branch: master
    branch: frewsxcv-publish
